export const countryList = [
  {
    label: 'Africa',
    options: [
      { value: 'Nigeria', label: 'Nigeria' },
      { value: 'Ethiopia', label: 'Ethiopia' },
      { value: 'Egypt', label: 'Egypt' },
      { value: 'DR Congo', label: 'DR Congo' },
      { value: 'Tanzania', label: 'Tanzania' },
      { value: 'South Africa', label: 'South Africa' },
      { value: 'Kenya', label: 'Kenya' },
      { value: 'Uganda', label: 'Uganda' },
      { value: 'Algeria', label: 'Algeria' },
      { value: 'Sudan', label: 'Sudan' },
      { value: 'Morocco', label: 'Morocco' },
      { value: 'Angola', label: 'Angola' },
      { value: 'Mozambique', label: 'Mozambique' },
      { value: 'Ghana', label: 'Ghana' },
      { value: 'Madagascar', label: 'Madagascar' },
      { value: 'Cameroon', label: 'Cameroon' },
      { value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
      { value: 'Niger', label: 'Niger' },
      { value: 'Burkina Faso', label: 'Burkina Faso' },
      { value: 'Mali', label: 'Mali' },
      { value: 'Malawi', label: 'Malawi' },
      { value: 'Zambia', label: 'Zambia' },
      { value: 'Senegal', label: 'Senegal' },
      { value: 'Chad', label: 'Chad' },
      { value: 'Somalia', label: 'Somalia' },
      { value: 'Zimbabwe', label: 'Zimbabwe' },
      { value: 'Guinea', label: 'Guinea' },
      { value: 'Rwanda', label: 'Rwanda' },
      { value: 'Benin', label: 'Benin' },
      { value: 'Burundi', label: 'Burundi' },
      { value: 'Tunisia', label: 'Tunisia' },
      { value: 'South Sudan', label: 'South Sudan' },
      { value: 'Togo', label: 'Togo' },
      { value: 'Sierra Leone', label: 'Sierra Leone' },
      { value: 'Libya', label: 'Libya' },
      { value: 'Congo', label: 'Congo' },
      { value: 'Liberia', label: 'Liberia' },
      { value: 'Central African Republic', label: 'Central African Republic' },
      { value: 'Mauritania', label: 'Mauritania' },
      { value: 'Eritrea', label: 'Eritrea' },
      { value: 'Namibia', label: 'Namibia' },
      { value: 'Gambia', label: 'Gambia' },
      { value: 'Botswana', label: 'Botswana' },
      { value: 'Gabon', label: 'Gabon' },
      { value: 'Lesotho', label: 'Lesotho' },
      { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
      { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
      { value: 'Mauritius', label: 'Mauritius' },
      { value: 'Eswatini', label: 'Eswatini' },
      { value: 'Djibouti', label: 'Djibouti' },
      { value: 'Comoros', label: 'Comoros' },
      { value: 'Cabo Verde', label: 'Cabo Verde' },
      { value: 'Sao Tome & Principe', label: 'Sao Tome & Principe' },
      { value: 'Seychelles', label: 'Seychelles' },
    ],
  },
  {
    label: 'Asia',
    options: [
      { value: 'China', label: 'China' },
      { value: 'India', label: 'India' },
      { value: 'Indonesia', label: 'Indonesia' },
      { value: 'Pakistan', label: 'Pakistan' },
      { value: 'Bangladesh', label: 'Bangladesh' },
      { value: 'Japan', label: 'Japan' },
      { value: 'Philippines', label: 'Philippines' },
      { value: 'Vietnam', label: 'Vietnam' },
      { value: 'Turkey', label: 'Turkey' },
      { value: 'Iran', label: 'Iran' },
      { value: 'Thailand', label: 'Thailand' },
      { value: 'Myanmar', label: 'Myanmar' },
      { value: 'South Korea', label: 'South Korea' },
      { value: 'Iraq', label: 'Iraq' },
      { value: 'Afghanistan', label: 'Afghanistan' },
      { value: 'Saudi Arabia', label: 'Saudi Arabia' },
      { value: 'Uzbekistan', label: 'Uzbekistan' },
      { value: 'Malaysia', label: 'Malaysia' },
      { value: 'Yemen', label: 'Yemen' },
      { value: 'Nepal', label: 'Nepal' },
      { value: 'North Korea', label: 'North Korea' },
      { value: 'Sri Lanka', label: 'Sri Lanka' },
      { value: 'Kazakhstan', label: 'Kazakhstan' },
      { value: 'Syria', label: 'Syria' },
      { value: 'Cambodia', label: 'Cambodia' },
      { value: 'Jordan', label: 'Jordan' },
      { value: 'Azerbaijan', label: 'Azerbaijan' },
      { value: 'United Arab Emirates', label: 'United Arab Emirates' },
      { value: 'Tajikistan', label: 'Tajikistan' },
      { value: 'Israel', label: 'Israel' },
      { value: 'Laos', label: 'Laos' },
      { value: 'Lebanon', label: 'Lebanon' },
      { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
      { value: 'Turkmenistan', label: 'Turkmenistan' },
      { value: 'Singapore', label: 'Singapore' },
      { value: 'Oman', label: 'Oman' },
      { value: 'State of Palestine', label: 'State of Palestine' },
      { value: 'Kuwait', label: 'Kuwait' },
      { value: 'Georgia', label: 'Georgia' },
      { value: 'Mongolia', label: 'Mongolia' },
      { value: 'Armenia', label: 'Armenia' },
      { value: 'Qatar', label: 'Qatar' },
      { value: 'Bahrain', label: 'Bahrain' },
      { value: 'Timor-Leste', label: 'Timor-Leste' },
      { value: 'Cyprus', label: 'Cyprus' },
      { value: 'Bhutan', label: 'Bhutan' },
      { value: 'Maldives', label: 'Maldives' },
      { value: 'Brunei', label: 'Brunei' },
    ],
  },
  {
    label: 'Europe',
    options: [
      { value: 'Germany', label: 'Germany' },
      { value: 'United Kingdom', label: 'United Kingdom' },
      { value: 'France', label: 'France' },
      { value: 'Italy', label: 'Italy' },
      { value: 'Spain', label: 'Spain' },
      { value: 'Ukraine', label: 'Ukraine' },
      { value: 'Poland', label: 'Poland' },
      { value: 'Romania', label: 'Romania' },
      { value: 'Netherlands', label: 'Netherlands' },
      { value: 'Belgium', label: 'Belgium' },
      { value: 'Czech Republic', label: 'Czech Republic' },
      { value: 'Greece', label: 'Greece' },
      { value: 'Portugal', label: 'Portugal' },
      { value: 'Sweden', label: 'Sweden' },
      { value: 'Hungary', label: 'Hungary' },
      { value: 'Belarus', label: 'Belarus' },
      { value: 'Austria', label: 'Austria' },
      { value: 'Serbia', label: 'Serbia' },
      { value: 'Switzerland', label: 'Switzerland' },
      { value: 'Bulgaria', label: 'Bulgaria' },
      { value: 'Denmark', label: 'Denmark' },
      { value: 'Finland', label: 'Finland' },
      { value: 'Slovakia', label: 'Slovakia' },
      { value: 'Norway', label: 'Norway' },
      { value: 'Ireland', label: 'Ireland' },
      { value: 'Croatia', label: 'Croatia' },
      { value: 'Moldova', label: 'Moldova' },
      { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
      { value: 'Albania', label: 'Albania' },
      { value: 'Lithuania', label: 'Lithuania' },
      { value: 'North Macedonia', label: 'North Macedonia' },
      { value: 'Slovenia', label: 'Slovenia' },
      { value: 'Latvia', label: 'Latvia' },
      { value: 'Estonia', label: 'Estonia' },
      { value: 'Montenegro', label: 'Montenegro' },
      { value: 'Luxembourg', label: 'Luxembourg' },
      { value: 'Malta', label: 'Malta' },
      { value: 'Iceland', label: 'Iceland' },
      { value: 'Andorra', label: 'Andorra' },
      { value: 'Monaco', label: 'Monaco' },
      { value: 'Liechtenstein', label: 'Liechtenstein' },
      { value: 'San Marino', label: 'San Marino' },
      { value: 'Holy See', label: 'Holy See' },
    ],
  },
  {
    label: 'Latin America',
    options: [
      { value: 'Brazil', label: 'Brazil' },
      { value: 'Mexico', label: 'Mexico' },
      { value: 'Colombia', label: 'Colombia' },
      { value: 'Argentina', label: 'Argentina' },
      { value: 'Peru', label: 'Peru' },
      { value: 'Venezuela', label: 'Venezuela' },
      { value: 'Chile', label: 'Chile' },
      { value: 'Guatemala', label: 'Guatemala' },
      { value: 'Ecuador', label: 'Ecuador' },
      { value: 'Bolivia', label: 'Bolivia' },
      { value: 'Haiti', label: 'Haiti' },
      { value: 'Cuba', label: 'Cuba' },
      { value: 'Dominican Republic', label: 'Dominican Republic' },
      { value: 'Honduras', label: 'Honduras' },
      { value: 'Paraguay', label: 'Paraguay' },
      { value: 'Nicaragua', label: 'Nicaragua' },
      { value: 'El Salvador', label: 'El Salvador' },
      { value: 'Costa Rica', label: 'Costa Rica' },
      { value: 'Panama', label: 'Panama' },
      { value: 'Uruguay', label: 'Uruguay' },
      { value: 'Jamaica', label: 'Jamaica' },
      { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
      { value: 'Guyana', label: 'Guyana' },
      { value: 'Suriname', label: 'Suriname' },
      { value: 'Belize', label: 'Belize' },
      { value: 'Bahamas', label: 'Bahamas' },
      { value: 'Barbados', label: 'Barbados' },
      { value: 'Saint Lucia', label: 'Saint Lucia' },
      { value: 'Grenada', label: 'Grenada' },
      { value: 'St. Vincent & Grenadines', label: 'St. Vincent & Grenadines' },
      { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
      { value: 'Dominica', label: 'Dominica' },
      { value: 'Saint Kitts & Nevis', label: 'Saint Kitts & Nevis' },
    ],
  },
  {
    label: 'Oceania',
    options: [
      { value: 'Australia', label: 'Australia' },
      { value: 'Papua New Guinea', label: 'Papua New Guinea' },
      { value: 'New Zealand', label: 'New Zealand' },
      { value: 'Fiji', label: 'Fiji' },
      { value: 'Solomon Islands', label: 'Solomon Islands' },
      { value: 'Micronesia', label: 'Micronesia' },
      { value: 'Vanuatu', label: 'Vanuatu' },
      { value: 'Samoa', label: 'Samoa' },
      { value: 'Kiribati', label: 'Kiribati' },
      { value: 'Tonga', label: 'Tonga' },
      { value: 'Marshall Islands', label: 'Marshall Islands' },
      { value: 'Palau', label: 'Palau' },
      { value: 'Tuvalu', label: 'Tuvalu' },
      { value: 'Nauru', label: 'Nauru' },
    ],
  },
  {
    label: 'Northern America',
    options: [
      { value: 'United States', label: 'United States' },
      { value: 'Canada', label: 'Canada' },
    ],
  },
];

export const domainList = [
  { value: 'Factory & plants', label: 'Factory & plants' },
  { value: 'Building & construction', label: 'Building & construction' },
  { value: 'Education', label: 'Education' },
  { value: 'Security', label: 'Security' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Sport', label: 'Sport' },
  { value: 'Communication', label: 'Communication' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Sales', label: 'Sales' },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Finance/economics', label: 'Finance/economics' },
  { value: 'Fashion', label: 'Fashion' },
  { value: 'Logistics', label: 'Logistics' },
  { value: 'Partnership', label: 'Partnership' },
];
