export const strings = {
  title: 'SpaceBooking',
  subtitle: 'space utilization management system',
  titleAbout: 'About the project',
  descriptionAbout1:
    'The project implies creation of a service with two roles (admin and the user) that allows employees to ',
  descriptionAbout1Bold: 'reserve a place for meetings ',
  descriptionAbout2: 'or coworking purposes and ',
  descriptionAbout2Bold: 'manage ',
  descriptionAbout3: 'their ',
  descriptionAbout3Bold: 'bookings ',
  descriptionAbout4: 'in real time.',
  subDescriptionAbout1: 'There is also an option of ',
  subDescriptionAbout1Bold: 'booking a custom parking space ',
  subDescriptionAbout2:
    'that takes into account the type and make of the vehicle.',
  six: '6',
  seven: '7',
  uk: 'UK',
  months: 'months',
  specialists: 'specialists',
  geography: 'geography ',
  titleBenefits: 'Project benefits',
  descriptionBenefits1:
    'The workspace management solution helps the project owner to plan, measure  and optimize their workplace space to',
  descriptionBenefitsBold:
    ' maximize workplace productivity and reduce operational costs.',
  descriptionBenefits2:
    ' It helps the employees book meeting rooms, work seats, and more.',
  bookingsRealized: 'Four main types of bookings were realized:',
  titleTimeline: 'Project timeline',
  phase1: 'phase 1',
  phase2: 'phase 2',
  months6: '6 months',
  design: 'Design',
  development: 'development',
  production: 'Production',
  inProgress: 'In progress...',
  mobileApp: 'Mobile app',
  webApp: 'Web app',
  months1: 'months',
  one: '1.5',
  five: '5',
  months5: 'months',
  inProgressMob: 'In progress',
  titleChallenges: 'Challenges and solutions',
  subTitleChallenges: 'faced during project development',
  titleFirstPhase: 'The main goal of the phase 1',
  descriptionFirstPhase:
    'To enable convenient and seamless booking of office space with the help of the ',
  descriptionFirstPhaseBold: 'web app.',
  titleFunctionality: 'Functionality',
  titleTechStack: 'Tech stack',
  titleResults: 'Results',
  desRes1: 'We have developed a two-role web application that enables ',
  desBoldRes1: 'convenient booking ',
  desRes2: 'of workspaces and ',
  desBoldRes2: 'managing ',
  desRes3: 'the process according to the present-day business demands.',
  titleTestimonials: 'Testimonials',
  titleFeatures: 'Features',
  titleOptionalFeatures: 'Optional features',
  subtitleOptionalFeatures: 'that can be added to similar project types',
  titleSecondPhase: 'To be continued...',
};

export const benefitsRealized = [
  {
    item: 'Day pass',
    className: 'itemDay',
  },
  {
    item: 'Parking space booking',
    className: 'itemParking',
  },
  {
    item: 'Visitor booking',
    className: 'itemVisitor',
  },
  {
    item: 'Meeting room booking',
    className: 'itemMeeting',
  },
];

export const challengesCards = [
  {
    title: 'Workspace booking system',
    boldTextOne:
      'Users can search for and book the workplace using various filters, ',
    boldTextTwo: 'Visitor booking: ',
    boldTextThree: 'Easy system of booking and reservations management. ',
    boldTextFour: "Ability to view last month's bookings ",
    boldTextMiddleOne: '',
    boldTextMiddleTwo: '',
    descriptionMiddleOne: '',
    descriptionMiddleTwo: '',
    description: '',
    descriptionOne:
      'like location within the office, date and room capacity. After they’ve made a decision which workspace to book, they mark it on the floor layout.',
    descriptionTwo:
      'registered users can make reservations for office visitors by applying the above principles.',
    descriptionThree:
      'The users can create, edit and delete reservations, change the number of attendees, as well as transfer the booked space to another person.',
    descriptionFour: 'for analytical comparisons of occupancy.',
    id: 1,
  },
  {
    title: 'Workplace availability',
    boldTextOne: '',
    boldTextTwo: '',
    boldTextThree: '',
    boldTextFour: '',
    boldTextMiddleOne: ' virtual layout of the building floors ',
    boldTextMiddleTwo: '',
    description: 'Creation of the',
    descriptionMiddleOne: '',
    descriptionMiddleTwo: '',
    descriptionOne:
      'and enabling the possibility of identifying and viewing the workplace location within the office.',
    descriptionTwo: '',
    descriptionThree: '',
    descriptionFour: '',
    id: 2,
  },
  {
    title: 'Customized parking space booking',
    boldTextOne: 'Customized parking space booking ',
    boldTextTwo: 'To allocate the parking space, ',
    boldTextThree: '',
    boldTextFour: '',
    boldTextMiddleOne: ' ',
    boldTextMiddleTwo: '',
    description: '',
    descriptionMiddleOne: '',
    descriptionMiddleTwo: '',
    descriptionOne:
      'feature (available for registered users and their guests): the possibility to reserve one or several parking spaces designated for specific types of vehicles.',
    descriptionTwo:
      'the app collects the following information: type (whether or not the vehicle is electric), vehicle make, color and registration number.',
    descriptionThree: '',
    descriptionFour: '',
    id: 3,
  },
  {
    title: 'Users management',
    boldTextOne: '',
    boldTextTwo: '',
    boldTextThree: '',
    boldTextFour: '',
    boldTextMiddleOne: 'registration possibility ',
    descriptionMiddleTwo: ' in order to book and use the space.',
    boldTextMiddleTwo: 'employees ',
    description: 'Enabling ',
    descriptionMiddleOne: 'for the company and its ',
    descriptionOne: '',
    descriptionTwo: '',
    descriptionThree: '',
    descriptionFour: '',
    id: 4,
  },
  {
    title: 'Contactless entry system',
    boldTextOne: '',
    boldTextTwo: '',
    boldTextThree: '',
    boldTextFour: '',
    boldTextMiddleOne: 'QR codes and motion sensors.',
    boldTextMiddleTwo: '',
    description: 'Unlocking the doors using ',
    descriptionMiddleOne: '',
    descriptionMiddleTwo: '',
    descriptionOne: '',
    descriptionTwo: '',
    descriptionThree: '',
    descriptionFour: '',
    id: 5,
  },
  {
    title: 'Property management',
    boldTextOne: '',
    boldTextTwo: '',
    boldTextThree: '',
    boldTextFour: '',
    boldTextMiddleOne: 'management of the entire floor to one person.',
    descriptionMiddleTwo: '',
    boldTextMiddleTwo: '',
    description: 'The possibility of entrusting the ',
    descriptionMiddleOne: '',
    descriptionOne: '',
    descriptionTwo: '',
    descriptionThree: '',
    descriptionFour: '',
    id: 6,
  },
];

export const challengesCardsTablet = [
  [
    {
      title: 'Workspace booking system',
      boldTextOne:
        'Users can search for and book the workplace using various filters, ',
      boldTextTwo: 'Visitor booking: ',
      boldTextThree: 'Easy system of booking and reservations management. ',
      boldTextFour: "Ability to view last month's bookings ",
      boldTextMiddleOne: '',
      boldTextMiddleTwo: '',
      descriptionMiddleOne: '',
      descriptionMiddleTwo: '',
      description: '',
      descriptionOne:
        'like location within the office, date and room capacity. After they’ve made a decision which workspace to book, they mark it on the floor layout.',
      descriptionTwo:
        'registered users can make reservations for office visitors by applying the above principles.',
      descriptionThree:
        'The users can create, edit and delete reservations, change the number of attendees, as well as transfer the booked space to another person.',
      descriptionFour: 'for analytical comparisons of occupancy.',
      id: 1,
      containerClasses: 'containerBooking',
      titleClasses: 'titleBooking',
    },
  ],
  [
    {
      title: 'Workplace availability',
      boldTextOne: '',
      boldTextTwo: '',
      boldTextThree: '',
      boldTextFour: '',
      boldTextMiddleOne: ' virtual layout of the building floors ',
      boldTextMiddleTwo: '',
      description: 'Creation of the',
      descriptionMiddleOne: '',
      descriptionMiddleTwo: '',
      descriptionOne:
        'and enabling the possibility of identifying and viewing the workplace location within the office.',
      descriptionTwo: '',
      descriptionThree: '',
      descriptionFour: '',
      id: 2,
      containerClasses: 'containerAvailability',
      titleClasses: 'titleAvailability',
    },
    {
      title: 'Customized parking space booking',
      boldTextOne: 'Customized parking space booking ',
      boldTextTwo: 'To allocate the parking space, ',
      boldTextThree: '',
      boldTextFour: '',
      boldTextMiddleOne: ' ',
      boldTextMiddleTwo: '',
      description: '',
      descriptionMiddleOne: '',
      descriptionMiddleTwo: '',
      descriptionOne:
        'feature (available for registered users and their guests): the possibility to reserve one or several parking spaces designated for specific types of vehicles.',
      descriptionTwo:
        'the app collects the following information: type (whether or not the vehicle is electric), vehicle make, color and registration number.',
      descriptionThree: '',
      descriptionFour: '',
      id: 3,
      containerClasses: 'containerParking',
      titleClasses: 'titleParking',
    },
  ],
  [
    {
      title: 'Users management',
      boldTextOne: '',
      boldTextTwo: '',
      boldTextThree: '',
      boldTextFour: '',
      boldTextMiddleOne: 'registration possibility ',
      descriptionMiddleTwo: ' in order to book and use the space.',
      boldTextMiddleTwo: 'employees ',
      description: 'Enabling ',
      descriptionMiddleOne: 'for the company and its ',
      descriptionOne: '',
      descriptionTwo: '',
      descriptionThree: '',
      descriptionFour: '',
      id: 4,
      containerClasses: 'containerUsers',
      titleClasses: 'titleUsers',
    },
    {
      title: 'Contactless entry system',
      boldTextOne: '',
      boldTextTwo: '',
      boldTextThree: '',
      boldTextFour: '',
      boldTextMiddleOne: 'QR codes and motion sensors.',
      boldTextMiddleTwo: '',
      description: 'Unlocking the doors using ',
      descriptionMiddleOne: '',
      descriptionMiddleTwo: '',
      descriptionOne: '',
      descriptionTwo: '',
      descriptionThree: '',
      descriptionFour: '',
      id: 5,
      containerClasses: 'containerContactless',
      titleClasses: 'titleContactless',
    },
    {
      title: 'Property management',
      boldTextOne: '',
      boldTextTwo: '',
      boldTextThree: '',
      boldTextFour: '',
      boldTextMiddleOne: 'management of the entire floor to one person.',
      descriptionMiddleTwo: '',
      boldTextMiddleTwo: '',
      description: 'The possibility of entrusting the ',
      descriptionMiddleOne: '',
      descriptionOne: '',
      descriptionTwo: '',
      descriptionThree: '',
      descriptionFour: '',
      id: 6,
      containerClasses: 'containerProperty',
      titleClasses: 'titleProperty',
    },
  ],
];

export const functionalityFirst = [
  {
    firstBold: 'User authorization. ',
    firstStr:
      'Registration in the WEB app is possible only by prior invitation.',
    secondBold: '',
    secondStr: '',
    id: 1,
    withLineTop: false,
  },
  {
    firstBold: '',
    firstStr: 'WEB ',
    secondBold: 'dashboard creation with booking statistics ',
    secondStr: 'for the past period.',
    id: 2,
    withLineTop: false,
  },
  {
    firstBold: '',
    firstStr: 'Ability to ',
    secondBold: 'monitor the workspace occupancy ',
    secondStr: 'at the layout in real time.',
    id: 3,
    withLineTop: false,
  },
  {
    firstBold: '',
    firstStr: 'Ability to ',
    secondBold: 'create, edit and delete rooms/workspace reservations ',
    secondStr: 'in the application.',
    id: 4,
    withLineTop: true,
  },
  {
    firstBold: '',
    firstStr: 'Filling in the ',
    secondBold: 'user/guest profile ',
    secondStr: 'details and entering vehicle information.',
    id: 5,
    withLineTop: false,
  },
];

export const functionalitySecond = [
  {
    firstBold: '',
    firstStr: 'Search by ',
    secondBold: 'filtering options, ',
    secondStr:
      'like type of workplace, number of people and date, with the ability to assign the space to both authorized and unauthorized persons.',
    id: 1,
    withLine: false,
    classesStrBefore: 'functionalitySecondStrBefore',
  },
  {
    firstBold: '',
    firstStr: 'Ability to ',
    secondBold: 'book a workplace for the whole day ',
    secondStr: '(Day pass).',
    id: 2,
    withLine: false,
    classesStrBefore: '',
  },
  {
    firstBold: '',
    firstStr: 'Ability to ',
    secondBold: 'configure: ',
    secondStr: 'messages, space types, integration, room and parking booking.',
    id: 3,
    withLine: false,
    classesStrBefore: '',
  },
  {
    firstBold: '',
    firstStr: 'Reservation of a ',
    secondBold: 'parking space according to the type of the vehicle.',
    secondStr: '',
    id: 4,
    withLine: true,
    classesStrBefore: '',
  },
];

export const techStack = [
  {
    src: '/images/projects/SpaceBooking/techStack/typescript.svg',
    title: 'TypeScript',
    delay: 0.3,
    id: 1,
    classesImg: '',
  },
  {
    src: '/images/projects/SpaceBooking/techStack/laravel.svg',
    title: 'Laravel',
    delay: 0.6,
    id: 2,
    classesImg: '',
  },
  {
    src: '/images/projects/SpaceBooking/techStack/php.svg',
    title: 'PHP',
    delay: 0.9,
    id: 3,
    classesImg: 'imgPhp',
  },
  {
    src: '/images/projects/SpaceBooking/techStack/mysql.svg',
    title: 'MYSQL',
    delay: 1.2,
    id: 4,
    classesImg: '',
  },
  {
    src: '/images/projects/SpaceBooking/techStack/bootstrap.svg',
    title: 'Bootstrap 5',
    delay: 1.5,
    id: 5,
    classesImg: 'imgBootstrap',
  },
  {
    src: '/images/projects/SpaceBooking/techStack/react.svg',
    title: 'React.js',
    delay: 1.8,
    id: 6,
    classesImg: 'imgReact',
  },
];

export const testimonialsCards = [
  {
    photo: '/images/projects/SpaceBooking/testimonials/john.svg',
    feedback:
      '“BandaPixels proved to be a reliable IT partner. The work on the project was consistent and all the milestones were met on schedule. The project manager and development team were professional, experienced and attentive to detail. We had a lot of discussions and our ideas were really listened to and put to practice. We are very happy with the project outcome and are planning to continue cooperation with BandaPixels in the future.” ',
    name: 'John R.',
    job: 'VP of Growth',
    id: 1,
  },
  {
    photo: '/images/projects/SpaceBooking/testimonials/alexandra.svg',
    feedback:
      '“BandaPixels is a company of consummate professionals. They took on responsibility for quite a challenging project and completed it with flying colors. The team showed a high level of work ethics and was wonderful to work with. The development process flowed very smoothly. We would rate BandaPixels as one of the best software companies we’ve worked with. "',
    name: 'Alexandra W.',
    job: 'Key Accounts Relationship Manager',
    id: 2,
  },
];

export const testimonialsCardsTablet = [
  {
    photo: '/images/projects/SpaceBooking/testimonials/john_t.svg',
    feedback:
      '“BandaPixels proved to be a reliable IT partner. The work on the project was consistent and all the milestones were met on schedule. The project manager and development team were professional, experienced and attentive to detail. We had a lot of discussions and our ideas were really listened to and put to practice. We are very happy with the project outcome and are planning to continue cooperation with BandaPixels in the future.” ',
    name: 'John R.',
    job: 'VP of Growth',
    id: 1,
    wrapperConsumerClasses: false,
  },
  {
    photo: '/images/projects/SpaceBooking/testimonials/alexandra_t.svg',
    feedback:
      '“BandaPixels is a company of consummate professionals. They took on responsibility for quite a challenging project and completed it with flying colors. The team showed a high level of work ethics and was wonderful to work with. The development process flowed very smoothly. We would rate BandaPixels as one of the best software companies we’ve worked with. "',
    name: 'Alexandra W.',
    job: 'Key Accounts Relationship Manager',
    id: 2,
    wrapperConsumerClasses: true,
  },
];

export const testimonialsCardsMobile = [
  {
    photo: '/images/projects/SpaceBooking/testimonials/john_m.svg',
    feedback:
      '“BandaPixels proved to be a reliable IT partner. The work on the project was consistent and all the milestones were met on schedule. The project manager and development team were professional, experienced and attentive to detail. We had a lot of discussions and our ideas were really listened to and put to practice. We are very happy with the project outcome and are planning to continue cooperation with BandaPixels in the future.” ',
    name: 'John R.',
    job: 'VP of Growth',
    id: 1,
    wrapperConsumerClasses: false,
    quoteClasses: '',
  },
  {
    photo: '/images/projects/SpaceBooking/testimonials/alexandra_m.svg',
    feedback:
      '“BandaPixels is a company of consummate professionals. They took on responsibility for quite a challenging project and completed it with flying colors. The team showed a high level of work ethics and was wonderful to work with. The development process flowed very smoothly. We would rate BandaPixels as one of the best software companies we’ve worked with. "',
    name: 'Alexandra W.',
    job: 'Key Accounts Relationship Manager',
    id: 2,
    wrapperConsumerClasses: true,
    quoteClasses: 'secondCardQuote',
  },
];

export const featuresLeft = [
  {
    firstBold: '',
    firstStr: 'User profiles',
    secondBold: '',
    secondStr: '',
    id: 1,
    withLineFeaturesLeft: false,
  },
  {
    firstBold: '',
    firstStr: 'Authorization',
    secondBold: '',
    secondStr: '',
    id: 2,
    withLineFeaturesLeft: false,
  },
  {
    firstBold: '',
    firstStr: 'Search and filtering',
    secondBold: '',
    secondStr: '',
    id: 3,
    withLineFeaturesLeft: true,
  },
  {
    firstBold: '',
    firstStr: 'Calendar of bookings',
    secondBold: '',
    secondStr: '',
    id: 4,
    withLineFeaturesLeft: false,
  },
  {
    firstBold: '',
    firstStr: 'Office space booking',
    secondBold: '',
    secondStr: '',
    id: 5,
    withLineFeaturesLeft: false,
  },
  {
    firstBold: '',
    firstStr: 'Custom parking space booking',
    secondBold: '',
    secondStr: '',
    id: 6,
    withLineFeaturesLeft: false,
  },
];

export const featuresRight = [
  {
    firstBold: '',
    firstStr: 'Іnteractive floor layout',
    secondBold: '',
    secondStr: '',
    id: 1,
    withLineFeaturesRight: true,
  },
  {
    firstBold: '',
    firstStr: 'Automation of processes for clients & guests',
    secondBold: '',
    secondStr: '',
    id: 2,
    withLineFeaturesRight: false,
  },
  {
    firstBold: '',
    firstStr: 'Gathering statistics on booking in the past periods',
    secondBold: '',
    secondStr: '',
    id: 3,
    withLineFeaturesRight: false,
  },
  {
    firstBold: '',
    firstStr: 'QR codes generation',
    secondBold: '',
    secondStr: '',
    id: 4,
    withLineFeaturesRight: false,
  },
  {
    firstBold: '',
    firstStr: 'Internet of Things integration',
    secondBold: '',
    secondStr: '',
    id: 5,
    withLineFeaturesRight: false,
  },
];

export const optionalFeatures = [
  {
    firstBold: 'Rent ',
    firstStr:
      '— service for landlord/tenants for management of payments, scheduling service of premises and availability of rental spaces.',
    secondBold: '',
    secondStr: '',
    id: 1,
  },
  {
    firstBold: 'E-commerce ',
    firstStr: '— online platform for selling products and services.',
    secondBold: '',
    secondStr: '',
    id: 2,
  },
  {
    firstBold: 'Analytics ',
    firstStr: '— data tracking, management and processing.',
    secondBold: '',
    secondStr: '',
    id: 3,
  },
  {
    firstBold: 'Management ',
    firstStr: '— rental spaces management.',
    secondBold: '',
    secondStr: '',
    id: 4,
  },
  {
    firstBold: 'Mortgage calculators.',
    firstStr: '',
    secondBold: '',
    secondStr: '',
    id: 5,
  },
  {
    firstBold: 'Security ',
    firstStr: '— surveillance, concierge, guard.',
    secondBold: '',
    secondStr: '',
    id: 6,
  },
  {
    firstBold: 'Booking ',
    firstStr: '— online booking for viewing.',
    secondBold: '',
    secondStr: '',
    id: 7,
  },
  {
    firstBold: 'Video streaming ',
    firstStr:
      '— a continuous transmission of video files from a server to a client.',
    secondBold: '',
    secondStr: '',
    id: 8,
  },
  {
    firstBold: 'Advanced data search and geo-mapping.',
    firstStr: '',
    secondBold: '',
    secondStr: '',
    id: 9,
  },
];
