export const constantsRoutes = {
  services: '/services',
  projects: '/projects',
  realEstate: '/real-estate',
  realEstateId: '/real-estate/[id]',
  blog: '/blog',
  blogId: '/blog/[id]',
  careers: '/careers',
  contacts: '/contacts',
  form: '/form',
  gastehaus: '/gastehaus',
  appnavi: '/appnavi',
  arxonas: '/arxonas',
  sunup: '/sunup',
  dcr: '/dcr',
  shed: '/shed',
  bree: '/bree',
  spacebooking: '/spacebooking',
  hotelCommunityPlatform: '/hotel',
  insidely: '/insidely',
  error: '/404',
};
