export const constants = {
  figuresMain: [
    {
      id: 1,
      duration: 1,
      delay: 1,
      style: {
        background: '#58D382',
        borderRadius: '0 120px 120px 0',
        top: 0,
        left: 0,
      },
    },
    {
      id: 2,
      duration: 2.4,
      delay: 1.1,
      style: {
        background: '#FBD347',
        borderRadius: '0 0 120px 120px',
        height: '90px',
        top: '200px',
        left: '192px',
      },
    },
    {
      id: 3,
      duration: 1.5,
      delay: 1.2,
      style: {
        background: 'transparent',
        borderRadius: '0 120px 120px 120px',
        border: '40px solid #C653B9',
        top: '0',
        left: '384px',
      },
    },
    {
      id: 4,
      duration: 2.4,
      delay: 1.3,
      style: {
        background: '#3F53D9',
        top: '192px',
        left: '384px',
        borderRadius: '120px 120px 120px 0',
      },
    },
    {
      id: 5,
      duration: 1.8,
      delay: 1.4,
      style: {
        background: '#FBD347',
        borderRadius: '120px 120px 0 0',
        height: '90px',
        top: '290px',
        left: '576px',
      },
    },
    {
      id: 6,
      duration: 3.4,
      delay: 1.5,
      style: {
        background: '#C653B9',
        top: '192px',
        left: '768px',
        borderRadius: '120px 120px 0 120px',
      },
    },
    {
      id: 7,
      duration: 2.5,
      delay: 1.6,
      style: {
        background: 'transparent',
        borderRadius: '120px 0 120px  120px',
        border: '40px solid #FBD347',
        top: 0,
        left: '990px',
      },
    },
    {
      id: 8,
      duration: 1.3,
      delay: 1.7,
      style: {
        background: '#3F53D9',
        top: '192px',
        left: '990px',
        borderRadius: '120px 120px 120px 0',
      },
    },
    {
      id: 9,
      duration: 2,
      delay: 1.8,
      style: {
        background: '#58D382',
        borderRadius: '120px 120px 0 0',
        height: '90px',
        top: '290px',
        left: '1180px',
      },
    },
    {
      id: 10,
      duration: 1.4,
      delay: 1.9,
      style: {
        background: 'transparent',
        borderRadius: '120px 0 120px  120px',
        border: '40px solid #58D382',
        top: '192px',
        left: '1600px',
      },
    },
    {
      id: 11,
      duration: 3,
      delay: 2,
      style: {
        background: '#FBD347',
        borderRadius: '0 120px 120px 120px',
        top: '192px',
        left: '1380px',
      },
    },
    {
      id: 12,
      duration: 1.3,
      delay: 2.1,
      style: {
        background: '#3F53D9',
        borderRadius: '120px 120px 0 0;',
        top: 0,
        left: 0,
      },
    },
  ],
  aboutProjects: [
    {
      id: 1,
      duration: 1,
      count: 'US',
      text: 'geography',
      color: '#3F53D9',
    },
    {
      id: 2,
      duration: 1.2,
      count: '7',
      text: 'months',
      color: '#C653B9',
    },
    {
      id: 3,
      duration: 1.4,
      count: '5',
      text: 'specialists',
      color: '#FBD347',
    },
    {
      id: 4,
      duration: 1.6,
      count: '10',
      text: 'technologies',
      color: '#58D382',
    },
  ],
  timeline: [
    {
      id: 1,
      name: 'Design',
      months: '2 months',
      color: '#3F53D9',
      duration: 1,
      delay: 1,
    },
    {
      id: 2,
      name: 'Back-end development',
      months: '4 months',
      color: '#FBD347',
      duration: 1,
      delay: 1.2,
    },
    {
      id: 3,
      name: 'Front-end development',
      months: '3 months',
      color: '#C653B9',
      duration: 1,
      delay: 1.4,
    },
    {
      id: 4,
      name: 'Production',
      months: '0,5 month',
      color: '#58D382',
      duration: 1,
      delay: 1.6,
    },
  ],
  goals: [
    {
      id: 1,
      image: '/images/projects/Insidely/message.png',
      text: 'streamline communication among staff members ',
      color: '#3F53D9',
      size: [40, 40],
      alt: 'stream',
      duration: 1,
    },
    {
      id: 2,
      image: '/images/projects/Insidely/clock.png',
      text: 'organize more efficient shift work',
      color: '#C653B9',
      size: [40, 40],
      alt: 'organize',
      duration: 1.2,
    },
    {
      id: 3,
      image: '/images/projects/Insidely/grid.png',
      text: 'achieve accountability and trackability of housekeeping operations',
      color: '#FBD347',
      size: [40, 40],
      alt: '',
      duration: 1.4,
    },
    {
      id: 4,
      image: '/images/projects/Insidely/services.png',
      text: 'improve maintenance services',
      color: '#58D382',
      size: [40, 40],
      alt: 'services',
      duration: 1.6,
    },
    {
      id: 5,
      image: '/images/projects/Insidely/book.png',
      text: 'facilitate training of new staff members',
      color: '#3F53D9',
      size: [40, 40],
      alt: 'book',
      duration: 1.8,
    },
    {
      id: 6,
      image: '/images/projects/Insidely/star.png',
      text: 'upgrade hotel service excellence',
      color: '#C653B9',
      size: [40, 40],
      alt: 'excellence',
      duration: 2,
    },
  ],
  stack: [
    {
      id: 1,
      duration: 1,
      image: '/images/projects/Insidely/html.svg',
      text: 'HTML5',
      background: '#3F53D9',
      size: [240, 240],
      borderRadius: '120px 120px 0px 120px',
      alt: 'HTML5',
    },
    {
      id: 2,
      duration: 1,
      image: '/images/projects/Insidely/sass.svg',
      text: 'SCSS',
      background: '#C653B9',
      size: [240, 240],
      alt: 'SCSS',
      borderRadius: '120px 120px 120px 0px',
    },
    {
      id: 3,
      duration: 1,
      image: '/images/projects/Insidely/express.svg',
      text: 'Express',
      background: '#FBD347',
      color: '#333333',
      size: [240, 240],
      alt: 'Express',
      borderRadius: '120px 120px 0px 0px',
    },
    {
      id: 4,
      duration: 1,
      image: '/images/projects/Insidely/angular.svg',
      text: 'Angular 10 ',
      background: '#C653B9',
      size: [240, 240],
      alt: 'Angular 10 ',
      borderRadius: '120px 120px 0px 120px',
    },
    {
      id: 5,
      duration: 1,
      image: '/images/projects/Insidely/mongo.svg',
      text: 'MongoDB',
      background: '#3F53D9',
      size: [240, 240],
      alt: 'MongoDB',
      borderRadius: '120px 120px 120px 0px',
    },

    {
      id: 6,
      duration: 1.2,
      image: '/images/projects/Insidely/node.svg',
      text: 'Node JS',
      background: '#3F53D9',
      size: [240, 240],
      alt: 'Node JS',
      borderRadius: '120px 0px 120px 120px',
    },
    {
      id: 7,
      duration: 1.2,
      image: '/images/projects/Insidely/ts.svg',
      text: 'Typescript',
      background: '#C653B9',
      size: [240, 240],
      alt: 'Typescript',
      borderRadius: '0px 120px 120px 120px',
    },
    {
      id: 8,
      duration: 1.2,
      image: '/images/projects/Insidely/mongoose.svg',
      text: 'Mongoose',
      background: '#58D382',
      color: '#333333',
      size: [240, 240],
      alt: 'Mongoose',
      borderRadius: '0px 0px 120px 120px',
    },
    {
      id: 9,
      duration: 1.2,
      image: '/images/projects/Insidely/figma.svg',
      text: 'Figma',
      background: '#C653B9',
      size: [240, 240],
      alt: 'Figma',
      borderRadius: '120px 0px 120px 120px',
    },
    {
      id: 10,
      duration: 1.2,
      image: '/images/projects/Insidely/aws.svg',
      text: 'AWS (S3)',
      background: '#3F53D9',
      size: [240, 240],
      alt: 'AWS (S3)',
      borderRadius: '0px 120px 120px 120px',
    },
  ],
  stack2: [
    {
      id: 1,
      first: {
        id: 1,
        duration: 1,
        image: '/images/projects/Insidely/html.svg',
        text: 'HTML5',
        background: '#3F53D9',
        size: [240, 240],
        borderRadius: '120px 120px 0px 120px',
        alt: 'HTML5',
      },
      second: {
        id: 6,
        duration: 1.2,
        image: '/images/projects/Insidely/node.svg',
        text: 'Node JS',
        background: '#3F53D9',
        size: [240, 240],
        alt: 'Node JS',
        borderRadius: '120px 0px 120px 120px',
      },
    },
    {
      id: 2,
      first: {
        id: 2,
        duration: 1,
        image: '/images/projects/Insidely/sass.svg',
        text: 'SCSS',
        background: '#C653B9',
        size: [240, 240],
        alt: 'SCSS',
        borderRadius: '120px 120px 120px 0px',
      },
      second: {
        id: 7,
        duration: 1.2,
        image: '/images/projects/Insidely/ts.svg',
        text: 'Typescript',
        background: '#C653B9',
        size: [240, 240],
        alt: 'Typescript',
        borderRadius: '0px 120px 120px 120px',
      },
    },
    {
      id: 3,
      first: {
        id: 3,
        duration: 1,
        image: '/images/projects/Insidely/express.svg',
        text: 'Express',
        background: '#FBD347',
        color: '#333333',
        size: [240, 240],
        alt: 'Express',
        borderRadius: '120px 120px 0px 0px',
      },
      second: {
        id: 8,
        duration: 1.2,
        image: '/images/projects/Insidely/mongoose.svg',
        text: 'Mongoose',
        background: '#58D382',
        color: '#333333',
        size: [240, 240],
        alt: 'Mongoose',
        borderRadius: '0px 0px 120px 120px',
      },
    },
    {
      id: 4,
      first: {
        id: 4,
        duration: 1,
        image: '/images/projects/Insidely/angular.svg',
        text: 'Angular 10 ',
        background: '#C653B9',
        size: [240, 240],
        alt: 'Angular 10 ',
        borderRadius: '120px 120px 0px 120px',
      },
      second: {
        id: 9,
        duration: 1.2,
        image: '/images/projects/Insidely/figma.svg',
        text: 'Figma',
        background: '#C653B9',
        size: [240, 240],
        alt: 'Figma',
        borderRadius: '120px 0px 120px 120px',
      },
    },
    {
      id: 5,
      first: {
        id: 5,
        duration: 1,
        image: '/images/projects/Insidely/mongo.svg',
        text: 'MongoDB',
        background: '#3F53D9',
        size: [240, 240],
        alt: 'MongoDB',
        borderRadius: '120px 120px 120px 0px',
      },
      second: {
        id: 10,
        duration: 1.2,
        image: '/images/projects/Insidely/aws.svg',
        text: 'AWS (S3)',
        background: '#3F53D9',
        size: [240, 240],
        alt: 'AWS (S3)',
        borderRadius: '0px 120px 120px 120px',
      },
    },
  ],
  figuresOptions: [
    {
      id: 1,
      duration: 1,
    },
    {
      id: 2,
      duration: 1.1,
    },
    {
      id: 3,
      duration: 1.2,
    },
    {
      id: 4,
      duration: 1.3,
    },
    {
      id: 5,
      duration: 1.4,
    },
    {
      id: 6,
      duration: 1.5,
    },
    {
      id: 7,
      duration: 1.6,
    },
    {
      id: 8,
      duration: 1.7,
    },
    {
      id: 9,
      duration: 1.8,
    },
    {
      id: 10,
      duration: 1.9,
    },
    {
      id: 11,
      duration: 2,
    },
    {
      id: 12,
      duration: 2.1,
    },
  ],
  socials: [
    {
      id: 1,
      duration: 1,
      image: '/images/projects/Insidely/linkedin.svg',
      background: 'socialBehance',
      size: [40, 40],
      alt: 'linkedin',
    },
    {
      id: 2,
      duration: 1.2,
      image: '/images/projects/Insidely/facebook.svg',
      background: 'socialLinkedin',
      size: [40, 40],
      alt: 'facebook',
    },
    {
      id: 3,
      duration: 1.4,
      image: '/images/projects/Insidely/whatsapp.svg',
      size: [40, 40],
      alt: 'whatsapp',
    },
    {
      id: 4,
      duration: 1.6,
      image: '/images/projects/Insidely/behance.svg',
      size: [40, 40],
      alt: 'behance',
    },
    {
      id: 5,
      duration: 1.8,
      image: '/images/projects/Insidely/dribbble.svg',
      size: [40, 40],
      alt: 'dribbble',
    },
  ],
  features: [
    {
      id: 1,
      duration: 1.2,
      name: 'Maintenance management:',
      dotColor: '#3F53D9',
      item: [
        'Maintenance issues reporting',
        'Notifications',
        'Preventive maintenance schedule',
        'Inventory control',
        'Contractors network',
        'Maintenance analytics',
      ],
    },
    {
      id: 2,
      duration: 1,
      name: 'Housekeeping management:',
      dotColor: '#3F53D9',
      item: [
        'Schedule of housekeeping tasks',
        'Tasks completion checklist',
        'Tasks commenting',
        'Housekeeping performance dashboards',
      ],
    },
    {
      id: 3,
      duration: 1.8,
      name: 'Handbook',
      dotColor: '#C653B9',
    },
    {
      id: 4,
      duration: 1.9,
      name: 'Staff chat',
      dotColor: '#C653B9',
    },

    {
      id: 5,
      duration: 2,
      name: 'Guests requests',
      dotColor: '#FBD347',
    },
    {
      id: 6,
      duration: 2,
      name: 'Digital handovers',
      dotColor: '#FBD347',
    },
    {
      id: 7,
      duration: 2.1,
      name: 'Complaints management',
      dotColor: '#58D382',
    },

    {
      id: 8,
      duration: 2.2,
      name: 'Checklists',
      dotColor: '#58D382',
    },
    {
      id: 9,
      duration: 2.4,
      name: 'News & Announcements',
      dotColor: '#3F53D9',
    },
  ],
};
